force-app/main/default/objects/TaskUser__mdt/TaskUser__mdt.object-meta.xml
<CustomObject>
    <description>Users that will be assigned tasks created by automated processes</description>
    <label>TaskUser</label>
    <pluralLabel>TaskUsers</pluralLabel>
</CustomObject>

force-app/main/default/objects/TaskUser__mdt/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <description>Task to assign the user</description>
    <label>Task</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Background check</fullName>
                <default>true</default>
                <label>Background check</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Admin Assistant</fullName>
                <label>Administrator Assistant</label>
            </value>
            <value>
                <fullName>Client Manager</fullName>
            </value>
            <value>
                <fullName>Inventory Admin</fullName>
            </value>
            <value>
                <fullName>TF Manager</fullName>
            </value>
            <value>
                <fullName>Trainer Manager</fullName>
            </value>
            <value>
                <fullName>Client Support Coordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskUser__mdt/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>Account id of the user to be assigned the task</description>
    <label>User</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tasks/TaskRepository.cls
public inherited sharing class TaskRepository {
    public Task[] create(Task[] tasks) {
        insert tasks;
        return tasks;
    }

    public Task[] getMatchingTasks(Id contactId, String subject) {
        return [SELECT Id, 
                       CreatedDate, 
                       OwnerId, 
                       Status, 
                       Subject
                FROM Task
                WHERE WhoId = :contactId AND Status <> 'Completed' AND Subject LIKE:subject];
    }

    // Find the user to assign a check tasks to
    public User getTaskUser(String task) {
        // Get the users to assign the task to
        TaskUser__mdt[] taskUsers = [SELECT User__c
                                     FROM TaskUser__mdt
                                     WHERE Task__c = :task];
        if (taskUsers.size() == 0) {
            System.debug('No ' + task + ' users defined in TaskUser__mdt');
            return null;
        }

        User[] users = [SELECT Id
                        FROM User
                        WHERE Username = :taskUsers[0].User__c AND IsActive = true];
        if (users.size() == 0) {
            System.debug('Cannot find user defined to assign background check reminder tasks');
            return null;
        }
        return users[0];
    }

}