force-app/main/default/objects/atlas1__BackgroundCheck__c/fields/atlas1__Type__c.field-meta.xml
<CustomField>
    <fullName>atlas1__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criminal</fullName>
                <default>true</default>
                <label>Criminal</label>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Criminal&amp;Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/pre/main/default/objects/Contact/fields/atlas1__VolunteerAccess__c.field-meta.xml
<CustomField>
    <fullName>atlas1__VolunteerAccess__c</fullName>
    <label>System Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations- Master Docs - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Operations- Financial</fullName>
            </value>
            <value>
                <fullName>Operations- Client</fullName>
            </value>
            <value>
                <fullName>Operations- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Operations- Trainer</fullName>
            </value>
            <value>
                <fullName>Board - READ ONLY</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Volunteer and Staff</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Trainer</fullName>
            </value>
            <value>
                <fullName>Sensitive Info- Board</fullName>
            </value>
            <value>
                <fullName>Active Projects- Academy</fullName>
            </value>
            <value>
                <fullName>Active Projects- ADI</fullName>
            </value>
            <value>
                <fullName>Active Projects- Branding and Marketing</fullName>
            </value>
            <value>
                <fullName>Active Projects- Client Certification</fullName>
            </value>
            <value>
                <fullName>Active Projects- Community Outreach and Education</fullName>
            </value>
            <value>
                <fullName>Active Projects- Dog Availability</fullName>
            </value>
            <value>
                <fullName>Active Projects- Fund Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Governance, Compliance and Operations</fullName>
            </value>
            <value>
                <fullName>Active Projects- Research and Development</fullName>
            </value>
            <value>
                <fullName>Active Projects- Scholarships</fullName>
            </value>
            <value>
                <fullName>Active Projects- State Registration</fullName>
            </value>
            <value>
                <fullName>Active Projects- Team Facilitator Certification</fullName>
            </value>
            <value>
                <fullName>Active Projects- Technology Infrastructure</fullName>
            </value>
            <value>
                <fullName>Active Projects- Trainer Certification</fullName>
            </value>
            <value>
                <fullName>Active Projects- Volunteer Recruitment and Retention</fullName>
            </value>
            <value>
                <fullName>Credit Check Required</fullName>
            </value>
            <value>
                <fullName>Background Check Required</fullName>
            </value>
            <value>
                <fullName>First Aid Required</fullName>
            </value>
            <value>
                <fullName>Combined Background Check Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskUser__mdt/TaskUser__mdt.object-meta.xml
<CustomObject>
    <description>Users that will be assigned tasks created by automated processes</description>
    <label>TaskUser</label>
    <pluralLabel>TaskUsers</pluralLabel>
</CustomObject>

force-app/main/default/objects/TaskUser__mdt/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <description>Task to assign the user</description>
    <label>Task</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Background check</fullName>
                <default>true</default>
                <label>Background check</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Admin Assistant</fullName>
                <label>Administrator Assistant</label>
            </value>
            <value>
                <fullName>Client Manager</fullName>
            </value>
            <value>
                <fullName>Inventory Admin</fullName>
            </value>
            <value>
                <fullName>TF Manager</fullName>
            </value>
            <value>
                <fullName>Trainer Manager</fullName>
            </value>
            <value>
                <fullName>Client Support Coordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskUser__mdt/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>Account id of the user to be assigned the task</description>
    <label>User</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/background-checks/BackgroundCheckService.cls
public with sharing class BackgroundCheckService {
    private BackgroundCheckRepository repo;
    private ContactRepository contactRepo;
    private TaskRepository taskRepo;

    public BackgroundCheckService() {
        this.repo = new BackgroundCheckRepository();
        this.contactRepo = new ContactRepository();
        this.taskRepo = new TaskRepository();
    }

    @TestVisible
    private BackgroundCheckService(BackgroundCheckRepository bgcrepo, ContactRepository contactRepo, TaskRepository taskRepo) {
        this.repo = bgcrepo;
        this.contactRepo = contactRepo;
        this.taskRepo = taskRepo;
    }

    public void createReminderTask() {
        atlas1__AtlasSettings__c settings = atlas1__AtlasSettings__c.getOrgDefaults();
        // check to see if this setting is missing
        if (settings.atlas1__BackgroundCheckRenewalYears__c == null) {
            settings.atlas1__BackgroundCheckRenewalYears__c = 1;
            upsert settings;
        }

        // find the cutoff for which background checks to remind
        Date threshold = Date.today().addYears(-1 * (Integer) settings.atlas1__BackgroundCheckRenewalYears__c).addMonths(1);

        // Get the users to assign the task to
        TaskUser__mdt taskUser = [SELECT User__c
                              FROM TaskUser__mdt
                              WHERE Task__c = 'Background check' LIMIT 1];
        User user = [SELECT Id
                        FROM User
                        WHERE Username = :taskUser.User__c AND IsActive = true Limit 1];

        // Make sure we only have one Background check per contact
        Set<Id> contactIds = new Set<Id>();
        Set<Id> creditIds = new Set<Id>();
        Set<Id> criminalIds = new Set<Id>();
        Set<Id> combinedIds = new Set<Id>();
        // Check for any contacts that need background checks
        Contact[] contacts = this.contactRepo.getContactsNeedingBackgroundChecks();

        for (Contact person : contacts) {
            contactIds.add(person.Id);
            if (person.atlas1__VolunteerAccess__c.contains('Credit Check Required') && person.atlas1__VolunteerAccess__c.contains('Background Check Required')) {
                combinedIds.add(person.Id);
                continue;
            }
            if (person.atlas1__VolunteerAccess__c.contains('Credit Check Required')) {
                creditIds.add(person.Id);
                continue;
            }
            if (person.atlas1__VolunteerAccess__c.contains('Background Check Required')) {
                criminalIds.add(person.Id);
            }
        }

        atlas1__BackgroundCheck__c[] checks = repo.getMatchingChecksForContacts(contactIds, threshold);

        // Remove the contacts with recent-enough background checks from the list
        for (atlas1__BackgroundCheck__c check : checks) {
            switch  on check.atlas1__Type__c {
                when 'Criminal&Credit' {
                    combinedIds.remove(check.atlas1__Contact__c);
                }
                when 'Criminal' {
                    criminalIds.remove(check.atlas1__Contact__c);
                }
                when 'Credit' {
                    creditIds.remove(check.atlas1__Contact__c);
                }
            }
        }

        // Find any existing tasks for these contacts
        Map<Id, Task[]> existingCreditTasks = taskRepo.getTasksByWhoId(creditIds, 'Order % check');

        // Create a list of Tasks
        Task[] tasks = new List<Task>();
        // Create tasks to order background checks
        for (Id contactId : criminalIds) {
            tasks.add(new Task(
                OwnerId = user.Id, 
                Subject = 'Order background check', 
                Status = 'Open', 
                Priority = 'Normal', 
                WhoId = contactId, 
                ActivityDate = Date.today()
            ));
        }
        // Create tasks to order credit checks
        for (Id contactId : creditIds) {
            tasks.add(new Task(
                OwnerId = user.Id, 
                Subject = 'Order credit check', 
                Status = 'Open', 
                Priority = 'Normal', 
                WhoId = contactId, 
                ActivityDate = Date.today()
            ));
        }

        taskRepo.create(tasks);
    }

}